### ISSUE TITLE
EasyPages width when in 'Article' page layout

### ISSUE THREAD

**Issue by mikezimm** [mikezimm/fps-library-v2#4]
## Should be this per testing in WebPart Testing

```css
.ep-drilldown {
    width: calc(100% - 60px);
}
```
