### ISSUE TITLE
Improve EasyAnalytics when using Pill Banner

### ISSUE THREAD

**Issue by mikezimm** [mikezimm/fps-library-v2#65]
![image](https://github.com/mikezimm/fps-library-v2/assets/49648086/76cf2fcf-590f-47ad-9611-8c9a85a3fdb5)

**Comment by mikezimm** [comment]
## Adjust this class but one step down

![image](https://github.com/mikezimm/fps-library-v2/assets/49648086/ba08f1d9-308e-4a98-862e-97d1e85ece99)

**Comment by mikezimm** [comment]
## Created this for common use.
However, EasyAnalytics won't need it because it will be under EasyPages.

```css
.bannerPillShapeSideMargin {
  margin-left: 20px;
  margin-right: 20px;
}
```
